---
kind: RoleBinding
# Change the following to match your K8s version
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-server-authn-role-binding
  namespace: testapp
subjects:
- kind: ServiceAccount
  name: conjur-cluster
  namespace: conjur-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-cluster-role
